josh=("9 august")
print("josh month's birthday:",josh)
bob=("1 june")
print("bob month's birthday:", bob)
zane=("23 july")
print("bob month's birthday:", zane)
domple=("16 september")
print("bob month's birthday:", domple)
samuel=("6 march")
print("bob month's birthday:", bob)